#!/usr/bin/env python

import os
import sys
import grp
from colors import bcolors

DOCKER_IMAGE    = "halsbrook"
DOCKER_NAME     = "app"


if __name__ == "__main__":
    # -----------------------------------
    # Ingresando a instancia
    # ----------------------------------------------------------------------------

    print bcolors.OKGREEN +  '=' * 70 + "\n" + bcolors.ENDC
    print bcolors.OKGREEN + "\n Ingresando al entorno "  + bcolors.ENDC

    os.system("docker exec -it " + DOCKER_NAME + " /bin/bash " ) #-  > /dev/null")

    print bcolors.OKGREEN + "\n\n Saliendo del entorno "  + bcolors.ENDC
    print bcolors.OKGREEN +  '=' * 70 + "\n" + bcolors.ENDC

# vim: se ft=python ts=4 sw=4 ai expandtab:

